version: "2.1"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  express:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:3000"
    links:
      - mongo
    depends_on:
      - mongo
